const quotes = [{"q":"It is better to change an opinion than to persist in a wrong one.","a":"Socrates","c":"65","h":"<blockquote>&ldquo;It is better to change an opinion than to persist in a wrong one.&rdquo; &mdash; <footer>Socrates</footer></blockquote>"},{"q":"Make your life a mission - not an intermission.","a":"Unknown","c":"47","h":"<blockquote>&ldquo;Make your life a mission - not an intermission.&rdquo; &mdash; <footer>Unknown</footer></blockquote>"},{"q":"There's a very deep connection among human beings. All we have to do is open our minds to it.","a":"Yanni","c":"93","h":"<blockquote>&ldquo;There's a very deep connection among human beings. All we have to do is open our minds to it.&rdquo; &mdash; <footer>Yanni</footer></blockquote>"},{"q":"Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.","a":"Les Brown","c":"108","h":"<blockquote>&ldquo;Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>"},{"q":"A good system shortens the road to the goal. ","a":"Orison Swett Marden","c":"45","h":"<blockquote>&ldquo;A good system shortens the road to the goal. &rdquo; &mdash; <footer>Orison Swett Marden</footer></blockquote>"},{"q":"Never say never, because limits, like fears, are often just an illusion.","a":"Michael Jordan","c":"72","h":"<blockquote>&ldquo;Never say never, because limits, like fears, are often just an illusion.&rdquo; &mdash; <footer>Michael Jordan</footer></blockquote>"},{"q":"The true soldier fights not because he hates what is in front of him, but because he loves what is behind him.","a":"Gilbert Chesterton","c":"110","h":"<blockquote>&ldquo;The true soldier fights not because he hates what is in front of him, but because he loves what is behind him.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>"},{"q":"If you try to get rid of fear and anger without knowing their meaning, they will grow stronger and return.","a":"Deepak Chopra","c":"106","h":"<blockquote>&ldquo;If you try to get rid of fear and anger without knowing their meaning, they will grow stronger and return.&rdquo; &mdash; <footer>Deepak Chopra</footer></blockquote>"},{"q":"If you run you stand a chance of losing, but if you don't run you've already lost.","a":"Barack Obama","c":"82","h":"<blockquote>&ldquo;If you run you stand a chance of losing, but if you don't run you've already lost.&rdquo; &mdash; <footer>Barack Obama</footer></blockquote>"},{"q":"First learn the meaning of what you say, and then speak.","a":"Epictetus","c":"56","h":"<blockquote>&ldquo;First learn the meaning of what you say, and then speak.&rdquo; &mdash; <footer>Epictetus</footer></blockquote>"}];

const quotesContainer = document.getElementById("quotes-container");

for (let i = 0; i < quotes.length; i++) {

    let quoteCard = `<div class="quote-card">
            <div class="quote">"${quotes[i].q}"</div>
            <p class="author">- <i>${quotes[i].a}</i></p>
            </div>
            `;

    quotesContainer.innerHTML += quoteCard;
}